= Service

NOTE: 이 섹션의 실습은 이전 섹션의 deploymets 생성을 따릅니다.

올바른 네임스페이스를 지정합니다.:

[#create-namespace]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc project myspace-%userid% 
----


Deployments가 있는지 확인하세요.:

[#have-deployment-service]
[.console-input]
[source,bash]
----
oc get deployments
----

[.console-output]
[source,bash]
----
NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
quarkus-demo-deployment   3/3     3            3           8m33s
----

Replicasets가 있는지 확인하세요:

[#have-rs-service]
[.console-input]
[source,bash]
----
oc get rs
----

[.console-output]
[source,bash]
----
NAME                                 DESIRED   CURRENT   READY   AGE
quarkus-demo-deployment-5979886fb7   3         3         3       8m56s
----

Pod가 있는지 확인하세요.:

[#have-pods-service]
[.console-input]
[source,bash]
----
oc get pods
----

[.console-output]
[source,bash]
----
NAME                                       READY   STATUS    RESTARTS   AGE
quarkus-demo-deployment-5979886fb7-c888m   1/1     Running   0          9m17s
quarkus-demo-deployment-5979886fb7-gdtnz   1/1     Running   0          9m17s
quarkus-demo-deployment-5979886fb7-grf59   1/1     Running   0          9m17s
----

서비스를 생성합니다.:
[#create-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  name: the-service
spec:
  selector:
    app: quarkus-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
EOF
----

:section-k8s: services
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
watch oc get services
----

[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME          TYPE           CLUSTER-IP      EXTERNAL-IP   PORT(S)          AGE
the-service   LoadBalancer   172.30.103.41   <pending>     80:31974/TCP     4s
----

외부 IP가 할당될 때까지 기다리세요.


[.console-output]
[source,bash,subs="+macros,+attributes"]
----
NAME    TYPE           CLUSTER-IP      EXTERNAL-IP     PORT(S)          AGE
myapp   LoadBalancer   172.30.103.41   34.71.122.153   8080:31974/TCP   44s
----

OpenShift와 같은 호스팅된 Kubernetes 클러스터를 사용하는 경우 `8080` 포트와 함께 `curl` 및 EXTERNAL-IP 주소를 사용하거나 `kubectl(oc)` 을 사용하여 가져옵니다.:

IMPORTANT: AWS에 있는 경우 `ip` 대신 `hostname` 을 가져와야 합니다. 아래 명령어는 hostname을 가져옵니다.


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
IP=$(kubectl get service the-service -o jsonpath="{.status.loadBalancer.ingress[0].hostname}")
----


[.console-input]
[source,bash,subs="+macros,+attributes"]
----
PORT=$(kubectl get service the-service -o jsonpath="{.spec.ports[*].port}")
----



Curl the Service:

[.console-input]
[source,bash,subs="+macros,+attributes"]
----
curl $IP:$PORT
----



결과값:

[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-grf59:1
----



== Ingress

[#create-ingress]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
cat <<EOF | kubectl apply -f -
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example
  namespace: myspace-%userid%
spec:
  rules:
    - host: stuff-myspace.apps.cluster-xjckc.xjckc.sandbox898.opentlc.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: the-service
                port:
                  number: 80
EOF
----

IMPORTANT: 상기 yaml을 적용하기 전에 `host: stuff-myspace.apps.cluster-xjckc.xjckc.sandbox898.opentlc.com` 부분 중, `cluster-xjckc.xjckc.sandbox898.opentlc.com` 부분은 클러스터마다 다르기 때문에 실제 사용중인 도메인 값으로 변경이 필요합니다.
도메인 값은 아래의 명령어 조회를 통해 확인할 수 있습니다.


[#curl-services-ingress]
[.console-input]
[source, bash]
----
oc whoami --show-console
----


[.console-output]
[source,bash]
----
https://console-openshift-console.apps.cluster-abcde.abcde.sandbox111.opentlc.com
----

IMPORTANT: 조회 된 값 중, `cluster-abcde.abcde.sandbox111.opentlc.com` 부분을 상기 yaml파일에 적용하여 사용하세요.
최종 적용 값은  `stuff-myspace.apps.cluster-abcde.abcde.sandbox111.opentlc.com` 이 되어야 합니다.


[#curl-services-ingress]
[.console-input]
[source, bash]
----
curl stuff-myspace.apps.cluster-abcde.abcde.sandbox111.opentlc.com
----

[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-gdtnz:2
----





== OpenShift Route

Delete the manually created Ingress to avoid any naming collisions.  An OpenShift Route leverages ha-proxy for its default Ingress.

[#delete-ingress]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
kubectl delete ingress myingress
----

[#expose-service]
[.console-input]
[source,bash,subs="+macros,+attributes"]
----
oc expose service the-service
kubectl get routes
----

[.console-output]
[source,bash]
----
NAME          HOST/PORT                                     PATH   SERVICES      PORT   TERMINATION   WILDCARD
the-service   the-service-myspace.apps.gcp.burrsutter.dev          the-service   8080                 None
----

Then make a request to the service:

[#curl-services-route]
[.console-input]
[source, bash]
----
curl the-service-myspace.apps.gcp.burrsutter.dev
----

[.console-output]
[source,bash]
----
Supersonic Subatomic Java with Quarkus quarkus-demo-deployment-5979886fb7-gdtnz:3
----

=== Use jq to pull out the data elements you need for scripting

[.console-input]
[source,bash]
----
kubectl get route the-service -o json > myroutes.json
----

Copy and paste contents into jqplay.org

https://www.screencast.com/t/09biZYHNo62

[#install-jq]
[.console-input]
[source, bash]
----
brew install jq
----

[#route-jq]
[.console-input]
[source, bash]
----
kubectl get route the-service -o json | jq '.spec.host'
"the-service-myspace.apps.gcp.burrsutter.dev"
----
